

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
      - name: Install Dependencies and Build Package
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry env use python
          poetry install
      - name: Run Tests
        run: |
          pip install .
          pytest
        
      - name: Build and Publish
        
        run: |
          poetry build
          poetry publish
on:
  push:
    branches:
    - main
